export interface Resident {
  id: string;
  firstName: string;
  middleName: string;
  lastName: string;
  birthDate: string;
  sex: 'Male' | 'Female';
  civilStatus: string;
  contactNumber: string;
  email?: string;
  residentType: 'Local' | 'Boarder' | 'Old Resident';
  isHeadOfFamily: boolean;
  familyId: string;
  qrCode: string;
  relationshipToHead: string;
  houseNumber: string;
  street: string;
  purok: string;
  city: string;
  province: string;
  vulnerableTypes?: string[];
  status: 'Active' | 'Inactive' | 'Transferred Out' | 'Deceased';
  dateRegistered: string;
  dateUpdated: string;
}

export const mockResidents: Resident[] = [
  {
    id: 'RES-001',
    firstName: 'Juan',
    middleName: 'Santos',
    lastName: 'Dela Cruz',
    birthDate: '1985-06-15',
    sex: 'Male',
    civilStatus: 'Married',
    contactNumber: '0917-123-4567',
    email: 'juan.delacruz@email.com',
    residentType: 'Local',
    isHeadOfFamily: true,
    familyId: 'FAM-001',
    qrCode: 'QR-FAM-001',
    relationshipToHead: 'Head',
    houseNumber: '123',
    street: 'Mabini Street',
    purok: 'Purok 1',
    city: 'Quezon City',
    province: 'Metro Manila',
    vulnerableTypes: [],
    status: 'Active',
    dateRegistered: '2024-01-15',
    dateUpdated: '2024-12-01',
  },
  {
    id: 'RES-002',
    firstName: 'Maria',
    middleName: 'Garcia',
    lastName: 'Dela Cruz',
    birthDate: '1987-08-22',
    sex: 'Female',
    civilStatus: 'Married',
    contactNumber: '0917-123-4567',
    email: 'maria.delacruz@email.com',
    residentType: 'Local',
    isHeadOfFamily: false,
    familyId: 'FAM-001',
    qrCode: 'QR-FAM-001',
    relationshipToHead: 'Spouse',
    houseNumber: '123',
    street: 'Mabini Street',
    purok: 'Purok 1',
    city: 'Quezon City',
    province: 'Metro Manila',
    vulnerableTypes: [],
    status: 'Active',
    dateRegistered: '2024-01-15',
    dateUpdated: '2024-12-01',
  },
  {
    id: 'RES-003',
    firstName: 'Pedro',
    middleName: 'Reyes',
    lastName: 'Santos',
    birthDate: '1950-03-10',
    sex: 'Male',
    civilStatus: 'Widow',
    contactNumber: '0918-234-5678',
    residentType: 'Local',
    isHeadOfFamily: true,
    familyId: 'FAM-002',
    qrCode: 'QR-FAM-002',
    relationshipToHead: 'Head',
    houseNumber: '456',
    street: 'Rizal Avenue',
    purok: 'Purok 2',
    city: 'Quezon City',
    province: 'Metro Manila',
    vulnerableTypes: ['Senior Citizen', 'PWD'],
    status: 'Active',
    dateRegistered: '2024-02-20',
    dateUpdated: '2024-11-15',
  },
  {
    id: 'RES-004',
    firstName: 'Ana',
    middleName: 'Lopez',
    lastName: 'Gonzales',
    birthDate: '1990-11-05',
    sex: 'Female',
    civilStatus: 'Single',
    contactNumber: '0919-345-6789',
    email: 'ana.gonzales@email.com',
    residentType: 'Local',
    isHeadOfFamily: true,
    familyId: 'FAM-003',
    qrCode: 'QR-FAM-003',
    relationshipToHead: 'Head',
    houseNumber: '789',
    street: 'Luna Street',
    purok: 'Purok 3',
    city: 'Quezon City',
    province: 'Metro Manila',
    vulnerableTypes: ['Solo Parent', 'Indigent'],
    status: 'Active',
    dateRegistered: '2024-03-10',
    dateUpdated: '2024-11-28',
  },
  {
    id: 'RES-005',
    firstName: 'Carlos',
    middleName: 'Mendoza',
    lastName: 'Ramos',
    birthDate: '1978-09-18',
    sex: 'Male',
    civilStatus: 'Single',
    contactNumber: '0920-456-7890',
    residentType: 'Boarder',
    isHeadOfFamily: false,
    familyId: 'FAM-004',
    qrCode: 'QR-FAM-004',
    relationshipToHead: 'Boarder',
    houseNumber: '321',
    street: 'Bonifacio Road',
    purok: 'Purok 4',
    city: 'Quezon City',
    province: 'Metro Manila',
    vulnerableTypes: [],
    status: 'Active',
    dateRegistered: '2024-04-05',
    dateUpdated: '2024-12-02',
  },
  {
    id: 'RES-006',
    firstName: 'Rosa',
    middleName: 'Cruz',
    lastName: 'Villanueva',
    birthDate: '1955-12-20',
    sex: 'Female',
    civilStatus: 'Married',
    contactNumber: '0921-567-8901',
    residentType: 'Local',
    isHeadOfFamily: false,
    familyId: 'FAM-005',
    qrCode: 'QR-FAM-005',
    relationshipToHead: 'Spouse',
    houseNumber: '654',
    street: 'Del Pilar Street',
    purok: 'Purok 1',
    city: 'Quezon City',
    province: 'Metro Manila',
    vulnerableTypes: ['Senior Citizen'],
    status: 'Active',
    dateRegistered: '2024-01-25',
    dateUpdated: '2024-11-20',
  },
  {
    id: 'RES-007',
    firstName: 'Jose',
    middleName: 'Torres',
    lastName: 'Martinez',
    birthDate: '1992-07-30',
    sex: 'Male',
    civilStatus: 'Married',
    contactNumber: '0922-678-9012',
    email: 'jose.martinez@email.com',
    residentType: 'Local',
    isHeadOfFamily: true,
    familyId: 'FAM-006',
    qrCode: 'QR-FAM-006',
    relationshipToHead: 'Head',
    houseNumber: '987',
    street: 'Aguinaldo Avenue',
    purok: 'Purok 2',
    city: 'Quezon City',
    province: 'Metro Manila',
    vulnerableTypes: [],
    status: 'Active',
    dateRegistered: '2024-05-12',
    dateUpdated: '2024-12-03',
  },
  {
    id: 'RES-008',
    firstName: 'Elena',
    middleName: 'Soriano',
    lastName: 'Bautista',
    birthDate: '1988-04-14',
    sex: 'Female',
    civilStatus: 'Single',
    contactNumber: '0923-789-0123',
    residentType: 'Local',
    isHeadOfFamily: true,
    familyId: 'FAM-007',
    qrCode: 'QR-FAM-007',
    relationshipToHead: 'Head',
    houseNumber: '135',
    street: 'Quezon Boulevard',
    purok: 'Purok 3',
    city: 'Quezon City',
    province: 'Metro Manila',
    vulnerableTypes: ['PWD'],
    status: 'Active',
    dateRegistered: '2024-06-08',
    dateUpdated: '2024-11-30',
  },
];
